src/St0iK/FoodosBundle/Entity/User.php
<?php
namespace St0iK\FoodosBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @param mixed $last_name
     */
    public function setLastName($last_name)
    {
        $this->last_name = $last_name;
    }
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $last_name;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }


    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * @param mixed $first_name
     */
    public function setFirstName($first_name)
    {
        $this->first_name = $first_name;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Returns the full name of a user
     */
    public function getFullName()
    {
        return ucfirst($this->first_name) . " " . ucfirst($this->last_name);
    }
}

src/St0iK/FoodosBundle/Resources/views/Admin/_partials/category_modal.html.twig
<div class="modal fade bs-example-modal-lg in" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">New Category</h4>
            </div>
            <div class="modal-body">
                <div class="bs-callout bs-callout-warning hidden">
                    <h4>Oh snap!</h4>
                    <p>This form seems to be invalid :(</p>
                </div>
                <form method="POST" class="ajaxCategoryAdd" action="{{ path('foodos_backend_admin_ajax_category_add') }}" {{ form_enctype(form) }}>
                {{ form_widget(form) }}
                <div class="showErrors"></div>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
                <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary"  id="save-new-category" v-on:click="categorySubmit">
                    <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate" style="display:none;"></span> Save</button>
            </div>
            {{ form_end(form) }}

        </div>
    </div>
</div>

src/St0iK/FoodosBundle/Resources/views/Admin/_partials/category_modal_edit.html.twig
 <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Update Category</h4>
            </div>
            <div class="modal-body">
                <form class="ajaxCategoryEdit" action="{{ path('foodos_backend_admin_ajax_category_edit', {'id': category.id}) }}">
                    <div id="st0ik_foodosbundle_category_edit">
                        {{ form_widget(form) }}
                    </div>
                </form>
            </div>
            <div class="modal-footer ">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary"  id="edit-category" v-on:click="categoryEditSubmit">
                    <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate" style="display:none;"></span> Save</button>
            </div>
            {{ form_end(form) }}

        </div>
    </div>

src/St0iK/FoodosBundle/Resources/views/Admin/_partials/footer.html.twig
<!-- footer content -->
<footer>
    <div class="pull-right">
        FoodOS - Dimitris Stoikidis
    </div>
    <div class="clearfix"></div>
</footer>
<!-- /footer content -->

src/St0iK/FoodosBundle/Resources/views/Admin/_partials/footer_buttons.html.twig
<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>
<!-- /menu footer buttons -->

src/St0iK/FoodosBundle/Resources/views/Admin/_partials/left_col.html.twig
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-apple"></i> <span>FoodOS</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="https://avatars3.githubusercontent.com/u/497785?v=3&u=4374c5c76df1ffa285232340512dce4d8d3b2dcb&s=400" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ app.user.firstName }}</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        {{ include('@Foodos/Admin/_partials/sidebar.html.twig') }}
        {{ include('@Foodos/Admin/_partials/footer_buttons.html.twig') }}

    </div>
</div>

src/St0iK/FoodosBundle/Resources/views/Admin/_partials/sidebar.html.twig
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>Store settings</h3>
        <ul class="nav side-menu">
            <li><a><i class="fa fa-home"></i> Catalog <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="{{ path('foodos_backend_admin_catalog') }}">Categories/Products</a></li>
                    <li><a href="/">Ingredients/Extras</a></li>
                </ul>
            </li>
        </ul>
    </div>

</div>
<!-- /sidebar menu -->

src/St0iK/FoodosBundle/Resources/views/Admin/_partials/top_navigation.html.twig
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="https://avatars3.githubusercontent.com/u/497785?v=3&u=4374c5c76df1ffa285232340512dce4d8d3b2dcb&s=400" alt="">
                        {{ app.user.fullName }}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="javascript:;"> Profile</a></li>
                        <li>
                            <a href="javascript:;">
                                <span class="badge bg-red pull-right">50%</span>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li><a href="javascript:;">Help</a></li>
                        <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>

                <li role="presentation" class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green">6</span>
                    </a>
                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <div class="text-center">
                                <a>
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->